# -*- coding: utf-8 -*-
"""Web_Scraping.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1lM-Qq8RoIR8byM01xzTjvArEOUKsY3lb
"""

# pip install google
from urllib.parse import urlparse

def is_unique(url, url_list):
    """
        To find whether a given url is a new website link or referring to some old website with internal links.
        Parameters
        ---------------------
        url : str - (url that needs to be checked)
        url_list : list - (list of all previously saved urls)
        ----------------------
        
        return  : bool
    """
    
    for i in range(len(url_list)):
        if url_list[i] in url:
            return False
        
    return True

try:
    from googlesearch import search
except ImportError:
    print("No module named 'google'")

#to search
# query = input("Enter any Query")
all_search_results = search(-q, tld="co.in",lang='en')

how_many_links = 10

unique_website_links = []

while len(unique_website_links) <= how_many_links:
    
    url = next(all_search_results)
    
    if is_unique(url, unique_website_links):
        unique_website_links.append(url)

print(unique_website_links)